### ISSUE TITLE
Minikube Stack fails "Cannot create resource events in API GROUP "" in the namespace "default"

### ISSUE THREAD

**Issue by clanstyles** [presslabs/stack#7] opened 2019-04-10 20:29 UTC
I've followed the standard minikube install and I'm getting:

```
E0410 20:28:02.661233       1 event.go:203] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"mysite.159436da5233f48f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Wordpress", Namespace:"default", Name:"mysite", UID:"0977333e-5bcf-11e9-acae-0800270cccbb", APIVersion:"wordpress.presslabs.org/v1alpha1", ResourceVersion:"1958", FieldPath:""}, Reason:"WPCronSyncSuccessfull", Message:"*v1beta1.CronJob default/mysite-wp-cron created successfully", Source:v1.EventSource{Component:"wordpress-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf23b254a750408f, ext:312951169, loc:(*time.Location)(0x1b77960)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf23b254a750408f, ext:312951169, loc:(*time.Location)(0x1b77960)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:serviceaccount:presslabs-stack:stack-wordpress-operator" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
```

**Comment by calind** [comment] 2019-04-12 13:10
Thanks for report. Looks like https://github.com/presslabs/wordpress-operator/blob/master/chart/wordpress-operator/templates/controller-clusterrole.yaml is missing the permission to create `Event` objects.

Would you attempt a PR at it?

**Comment by bogdanpetrea** [comment] 2019-07-08 12:19
This was fixed in https://github.com/presslabs/wordpress-operator/commit/4c0094828df72279df606a139b0d8ad9a8393484. I couldn't reproduce the issue any longer.

**Closed by bogdanpetrea** 2019-07-08 12:19 UTC
